const exerciseRegistry = [
    { id: 1, name: 'Bench Press', category: 'Chest', primary: ['Chest'], secondary: ['Triceps'], image: 'Assets/exercises/bench.png' },
    { id: 2, name: 'Back Squat', category: 'Legs', primary: ['Legs'], secondary: ['Core'], image: 'Assets/exercises/back-squat.png' },
    { id: 3, name: 'Romanian Deadlift (RDL)', category: 'Legs', primary: ['Legs'], secondary: ['Back'], image: 'Assets/exercises/rdl.png' },
    { id: 4, name: 'Incline Press', category: 'Chest', primary: ['Upper Chest'], secondary: ['Triceps'], image: 'Assets/exercises/incline-press.png' },
    { id: 5, name: 'Row', category: 'Back', primary: ['Back'], secondary: ['Biceps'], image: 'Assets/exercises/row.png' },
    { id: 6, name: 'Pulldown', category: 'Back', primary: ['Back'], secondary: ['Biceps'], image: 'Assets/exercises/pulldown.png' },
    { id: 7, name: 'Cable Fly', category: 'Chest', primary: ['Chest'], secondary: [], image: 'Assets/exercises/cable-fly.png' },
    { id: 8, name: 'Shoulder Press', category: 'Shoulders', primary: ['Shoulders'], secondary: ['Triceps'], image: 'Assets/exercises/shoulder-press.png' },
    { id: 9, name: 'Machine Chest Press', category: 'Chest', primary: ['Chest'], secondary: ['Triceps'], image: 'Assets/exercises/machine-chest-press.png' },
    { id: 10, name: 'Lateral Raise', category: 'Shoulders', primary: ['Shoulders'], secondary: [], image: 'Assets/exercises/lateral.png' },
    { id: 11, name: 'Rear Delt Fly', category: 'Shoulders', primary: ['Rear Delts'], secondary: ['Back'], image: 'Assets/exercises/rear-delt.png' },
    { id: 12, name: 'Face Pull', category: 'Shoulders', primary: ['Rear Delts'], secondary: ['Back'], image: 'Assets/exercises/face-pull.png' },
    { id: 13, name: 'Seated Cable Row', category: 'Back', primary: ['Back'], secondary: ['Biceps'], image: 'Assets/exercises/seated-cable-row.png' },
    { id: 14, name: 'Inverted Row', category: 'Back', primary: ['Back'], secondary: ['Biceps'], image: 'Assets/exercises/inverted-row.png' },
    { id: 15, name: 'Assisted Pull-Up', category: 'Back', primary: ['Back'], secondary: ['Biceps'], image: 'Assets/exercises/assisted-pullup.png' },
    { id: 16, name: 'Band Assisted Pull-Up', category: 'Back', primary: ['Back'], secondary: ['Biceps'], image: 'Assets/exercises/band-assisted-pullup.png' },
    { id: 17, name: 'Hammer Curl', category: 'Arms', primary: ['Biceps'], secondary: [], image: 'Assets/exercises/hammer-curl.png' },
    { id: 18, name: 'Curl', category: 'Arms', primary: ['Biceps'], secondary: [], image: 'Assets/exercises/curl.png' },
    { id: 19, name: 'Triceps Extension', category: 'Arms', primary: ['Triceps'], secondary: [], image: 'Assets/exercises/triceps.png' },
    { id: 20, name: 'Hack Squat', category: 'Legs', primary: ['Legs'], secondary: ['Glutes'], image: 'Assets/exercises/hack-squat.png' },
    { id: 21, name: 'Leg Press', category: 'Legs', primary: ['Legs'], secondary: [], image: 'Assets/exercises/leg-press.png' },
    { id: 22, name: 'Leg Extension', category: 'Legs', primary: ['Quadriceps'], secondary: [], image: 'Assets/exercises/leg-extension.png' },
    { id: 23, name: 'Bulgarian Split Squat', category: 'Legs', primary: ['Legs'], secondary: ['Glutes'], image: 'Assets/exercises/bulgarian-split.png' },
    { id: 24, name: 'Supported Split Squat', category: 'Legs', primary: ['Legs'], secondary: ['Glutes'], image: 'Assets/exercises/supported-split-squat.png' },
    { id: 25, name: 'Walking Lunge', category: 'Legs', primary: ['Legs'], secondary: ['Glutes'], image: 'Assets/exercises/walking-lunge.png' },
    { id: 26, name: 'Hip Thrust', category: 'Legs', primary: ['Glutes'], secondary: ['Hamstrings'], image: 'Assets/exercises/hip-thrust.png' },
    { id: 27, name: 'Calf Raise', category: 'Legs', primary: ['Calves'], secondary: [], image: 'Assets/exercises/calf-raise.png' },
    { id: 28, name: 'Box Pistol Squat', category: 'Legs', primary: ['Legs'], secondary: ['Balance'], image: 'Assets/exercises/box-pistol.png' },
    { id: 29, name: 'Forearm Plank', category: 'Core', primary: ['Core'], secondary: [], image: 'Assets/exercises/forearm-plank.png' },
    { id: 30, name: 'Hanging Knee Raise', category: 'Core', primary: ['Core'], secondary: [], image: 'Assets/exercises/hanging-knee-raise.png' },
    { id: 31, name: 'Hollow Hold', category: 'Core', primary: ['Core'], secondary: [], image: 'Assets/exercises/hollow-hold.png' },
    { id: 32, name: 'Mobility Arm Swings', category: 'Mobility', primary: ['Mobility'], secondary: [], image: 'Assets/exercises/mobility-arm-swings.png' },
    { id: 33, name: 'Mobility Body Waves', category: 'Mobility', primary: ['Mobility'], secondary: [], image: 'Assets/exercises/mobility-body-waves.png' },
    { id: 34, name: 'Mobility Dead Arms', category: 'Mobility', primary: ['Mobility'], secondary: [], image: 'Assets/exercises/mobility-dead-arms.png' },
    { id: 35, name: 'Mobility Fascia Slaps', category: 'Mobility', primary: ['Mobility'], secondary: [], image: 'Assets/exercises/mobility-fascia-slaps.png' },
    { id: 36, name: 'Mobility Golf Swings', category: 'Mobility', primary: ['Mobility'], secondary: [], image: 'Assets/exercises/mobility-golf-swings.png' },
    { id: 37, name: 'Mobility Hops', category: 'Mobility', primary: ['Mobility'], secondary: [], image: 'Assets/exercises/mobility-hops.png' },
    { id: 38, name: 'Mobility Knee Taps', category: 'Mobility', primary: ['Mobility'], secondary: [], image: 'Assets/exercises/mobility-knee-taps.png' },
    { id: 39, name: 'Mobility Plie Squats', category: 'Mobility', primary: ['Mobility'], secondary: [], image: 'Assets/exercises/mobility-plie-squats.png' },
    { id: 40, name: 'Mobility Side Lunges', category: 'Mobility', primary: ['Mobility'], secondary: [], image: 'Assets/exercises/mobility-side-lunges.png' },
    { id: 41, name: 'Mobility Toe Touches', category: 'Mobility', primary: ['Mobility'], secondary: [], image: 'Assets/exercises/mobility-toe-touches.png' },
    { id: 42, name: 'Mobility Trunk Twists', category: 'Mobility', primary: ['Mobility'], secondary: [], image: 'Assets/exercises/mobility-trunk-twists.png' },
    { id: 43, name: 'Active Hang', category: 'Other', primary: ['Grip'], secondary: [], image: 'Assets/exercises/active-hang.png' }
];
